//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajati_articole
    {
        public int Index { get; set; }
        public string AngajatID { get; set; }
        public string ArticolID { get; set; }
        public Nullable<System.DateTime> Data_Primire { get; set; }
        public string Cod_Primire { get; set; }
    
        public virtual Angajati Angajati { get; set; }
        public virtual Articole Articole { get; set; }
    }
}
