//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articole()
        {
            this.Angajati_articole = new HashSet<Angajati_articole>();
        }
    
        public int Index { get; set; }
        public string Cod_Produs { get; set; }
        public string Denumire { get; set; }
        public Nullable<System.DateTime> Data_In { get; set; }
        public Nullable<int> Valabilitate { get; set; }
        public string U_M { get; set; }
        public Nullable<int> Cantitate { get; set; }
        public Nullable<decimal> Pret { get; set; }
        public string CUI_Furnizor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Angajati_articole> Angajati_articole { get; set; }
        public virtual Furnizori Furnizori { get; set; }
    }
}
