//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestiuneEntities : DbContext
    {
        public GestiuneEntities()
            : base("name=GestiuneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Angajati> Angajati { get; set; }
        public virtual DbSet<Angajati_articole> Angajati_articole { get; set; }
        public virtual DbSet<Articole> Articole { get; set; }
        public virtual DbSet<Credentials> Credentials { get; set; }
        public virtual DbSet<Furnizori> Furnizori { get; set; }
    }
}
